# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-10 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='object_id',
            field=models.CharField(default=' ', max_length=100, primary_key=True, serialize=False, verbose_name='mainkey'),
        ),
    ]
