# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-10 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170410_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='liuyanxinxi',
            fields=[
                ('object_id', models.CharField(default=' ', max_length=100, primary_key=True, serialize=False, verbose_name='mainkey')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('address', models.CharField(max_length=30, verbose_name='address')),
                ('liuyan', models.CharField(max_length=500, verbose_name='liuyan')),
            ],
            options={
                'db_table': 'user',
                'verbose_name': 'User',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
