# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-10 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170410_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liuyanxinxi',
            old_name='liuyan',
            new_name='message',
        ),
    ]
