# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-10 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170410_1233'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='liuyanxinxi',
            new_name='message',
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'message'},
        ),
        migrations.AlterModelTable(
            name='message',
            table='message',
        ),
    ]
