# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-10 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20170410_1237'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='message',
            new_name='user_message',
        ),
    ]
