# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-15 01:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20170410_1307'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_message',
            table='user_message',
        ),
    ]
