# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-15 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20170415_0116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_message',
            options={'verbose_name': 'yonghu_message'},
        ),
    ]
