# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-15 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20170415_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('address', models.CharField(max_length=30, verbose_name='address')),
                ('message', models.CharField(max_length=500, verbose_name='liuyan')),
            ],
            options={
                'db_table': 'user_message',
                'verbose_name': 'yonghu_message',
            },
        ),
        migrations.DeleteModel(
            name='user_message',
        ),
    ]
