# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-15 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20170415_0959'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermessage',
            table=None,
        ),
    ]
