# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-15 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20170415_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='id',
        ),
        migrations.AddField(
            model_name='usermessage',
            name='object_id',
            field=models.CharField(default=' ', max_length=100, primary_key=True, serialize=False, verbose_name='mainkey'),
        ),
        migrations.AlterModelTable(
            name='usermessage',
            table='user_message',
        ),
    ]
