# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-15 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20170415_1003'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermessage',
            table='UserMessage',
        ),
    ]
