# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-18 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20170415_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name': '\u7528\u6237\u7559\u8a00', 'verbose_name_plural': '\u7528\u6237\u7559\u8a00'},
        ),
    ]
