# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-18 16:09
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20170418_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100)),
                ('Content', DjangoUeditor.models.UEditorField(default='', verbose_name='\u5185\u5bb9\t')),
            ],
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='message',
            field=DjangoUeditor.models.UEditorField(max_length=500, verbose_name='liuyan'),
        ),
    ]
