# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-18 16:51
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20170418_1609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='message',
            field=DjangoUeditor.models.UEditorField(default='', max_length=500, verbose_name='\u5185\u5bb9'),
        ),
    ]
