# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-18 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20170418_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name': 'UserMessage', 'verbose_name_plural': 'UserMessage'},
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='message',
            field=models.CharField(max_length=30, verbose_name='message'),
        ),
    ]
