# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-19 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20170418_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name': '\u7528\u6237\u8bc4\u8bba', 'verbose_name_plural': '\u7528\u6237\u8bc4\u8bba'},
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='address',
            field=models.CharField(max_length=30, verbose_name='\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='message',
            field=models.CharField(max_length=300, verbose_name='\u8bc4\u8bba'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='name',
            field=models.CharField(max_length=20, verbose_name='\u540d\u5b57'),
        ),
    ]
