# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-19 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20170419_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='address',
            field=models.CharField(max_length=30, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='message',
            field=models.CharField(max_length=300, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='name',
            field=models.CharField(max_length=20, verbose_name='name'),
        ),
    ]
