# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-20 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20170420_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='media/image/man.jpeg', upload_to='media/image/%Y/%m', verbose_name='\u5934\u50cf'),
        ),
    ]
