# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-19 21:11
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=200, verbose_name='pinglun')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='tianjiashijian')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='yonghu')),
            ],
            options={
                'verbose_name': 'pinglun',
                'verbose_name_plural': 'pinglun',
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_id', models.IntegerField(default=0, verbose_name='shujiuid')),
                ('fav_type', models.IntegerField(choices=[(1, 'yonghu'), (2, 'wenzhang')], default=1, verbose_name='shouchangleixing')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='shoucahngshijian')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='yonghu')),
            ],
            options={
                'verbose_name': 'yonghushouchang',
                'verbose_name_plural': 'yonghushouchang',
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0, verbose_name='jieshouyinghu')),
                ('message', models.CharField(max_length=500, verbose_name='xiaoxineirong')),
                ('has_read', models.BooleanField(default=False, verbose_name='shifouyidu')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='shoucahngshijian')),
            ],
            options={
                'verbose_name': 'yonghuxaioxi',
                'verbose_name_plural': 'yonghuxaioxi',
            },
        ),
    ]
