# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-21 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20170420_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': '\u7528\u6237\u8bc4\u8bba', 'verbose_name_plural': '\u7528\u6237\u8bc4\u8bba'},
        ),
    ]
