# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-23 11:19
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20170421_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='message',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='\u6d88\u606f\u5185\u5bb9'),
        ),
    ]
